# Generated by Django 4.1.5 on 2023-02-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0015_rename_quantity_product_stock'),
        ('orders', '0014_alter_orderclient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='website/logo/')),
                ('favicon', models.ImageField(upload_to='website/favicon/')),
                ('banner', models.ImageField(upload_to='website/banner/')),
                ('banner_title', models.CharField(max_length=50)),
                ('banner_subtitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='website/reviews/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderclient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PromotedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.product')),
            ],
        ),
    ]
