# Generated by Django 4.1.5 on 2023-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_review_image_alter_review_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Review Ratings',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddConstraint(
            model_name='reviewrating',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_range'),
        ),
    ]
