# Generated by Django 4.1.5 on 2023-02-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_reviewrating_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
