# Generated by Django 4.1.5 on 2023-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='website/logo/')),
                ('favicon', models.ImageField(upload_to='website/favicon/')),
                ('banner', models.ImageField(upload_to='website/banner/')),
                ('banner_title', models.CharField(max_length=50)),
                ('banner_subtitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
