# Generated by Django 4.1.5 on 2023-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_setting_banner_remove_setting_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('banner', 'Banner')], max_length=50, unique=True)),
                ('value', models.ImageField(upload_to='website/settings/')),
            ],
        ),
        migrations.CreateModel(
            name='TextSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(choices=[('banner_title', 'Banner Title'), ('banner_subtitle', 'Banner Subtitle')], max_length=50, unique=True)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
