# Generated by Django 4.1.5 on 2023-02-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_rename_quantity_product_stock'),
        ('website', '0008_imagesetting_textsetting_delete_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.product', unique=True),
        ),
        migrations.AlterField(
            model_name='textsetting',
            name='setting',
            field=models.CharField(choices=[('bannerTitle', 'Banner Title'), ('bannerSubtitle', 'Banner Subtitle')], max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
