# Generated by Django 4.1.5 on 2023-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(auto_created=True, blank=True, max_length=100,
                                   null=True, unique=True, verbose_name='Order ID (LEAVE EMPTY!)'),
        ),
    ]
