# Generated by Django 4.1.5 on 2023-01-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_category_options'),
        ('orders', '0007_remove_order_products_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(
                through='orders.OrderProduct', to='content.product'),
        ),
    ]
