# Generated by Django 4.1.5 on 2023-01-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderclient_remove_order_email_remove_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderclient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
