# Generated by Django 4.1.5 on 2023-01-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
