# Generated by Django 4.1.5 on 2023-01-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True,
                                   null=True, unique=True, verbose_name='Slug (Optional)'),
        ),
    ]
