# Generated by Django 4.1.5 on 2023-01-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_image_remove_product_image_delete_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True,
                 unique=True, verbose_name='Slug (Optional)')),
            ],
        ),
    ]
