# Generated by Django 4.1.5 on 2023-01-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
