# Generated by Django 4.1.5 on 2023-02-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
